const express = require('express');
const { apiAuth, requirePermission, requirePasswordChanged } = require('./middleware/apiAuth');
const { notFound } = require('./middleware/apiErrorHandler');
const session = require('./controllers/sessionApiController');
const tickets = require('./controllers/ticketApiController');
const equipment = require('./controllers/equipmentApiController');
const notifications = require('./controllers/notificationApiController');
const users = require('./controllers/userApiController');
const reports = require('./controllers/reportApiController');

const router = express.Router();
router.use(apiAuth);
router.param('id', require('./middleware/validateId'));
router.get('/session', session.show);
const ready = requirePasswordChanged;
router.get('/tickets', ready, tickets.list);
router.get('/tickets/:id', ready, tickets.show);
router.get('/equipment', ready, requirePermission('viewEquipment'), equipment.list);
router.get('/equipment/:id', ready, requirePermission('viewEquipment'), equipment.show);
router.get('/notifications', ready, notifications.list);
router.get('/users', ready, requirePermission('viewUsers'), users.list);
router.get('/users/:id', ready, requirePermission('viewUsers'), users.show);
router.get('/reports/summary', ready, requirePermission('viewReports'), reports.summary);
router.use(notFound);
module.exports = router;
